project_id = "rfrqemafmqcmmbgctrtt"

[functions.send-onboarding-complete-email]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.conferencia-inss-reminder]
verify_jwt = false

[functions.public-indicacao]
verify_jwt = false

[functions.pre-analise-elegibilidade]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false